#version: '3'
#services:
#  web:
#    build: .
#    
#    ports:
#      - "4000:4000"
#      - "3000:3000"
#    volumes:
#      - .:/app
#    links:
#      - localhost
#    
#    environment: 
#     - NODE_ENV=dev
#     - MIX_ENV=dev
#     
#    command: mix phx.server
#  localhost:
#    image: "postgres:10"
#    
#    container_name: base-postgres
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres

      
version: '3.2'
services:
  db:
    image: postgres

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command:
      - ./run.sh