version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - localhost
    command: mix phx.server
  localhost:
    image: "postgres:9.6.3"
    container_name: base-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"  

